config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Sidekiq Web UI, only for admins.
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # home route
  root to: 'pages#landing'

  get '/profile', to: 'pages#profile'

  # TMDB suggestions route after user selection of filters
  get '/tmdb_suggestions/:params', to: 'tmdb_suggestions#fetcher'

  # route to achievements
  get '/achievements', to: 'achievements#index'

  # routes related to 'History' button in navbar
  get '/history', to: 'saved_movies#history_index', as: 'history_index' #history index
  patch '/history/movie/update/:id', to: 'saved_movies#history_update', as: 'history_update' # change rating button SHOW (switch)
  patch '/history/movie/update_like/:id', to: 'saved_movies#history_update_like', as: 'history_update_like' # change rating button SHOW (like)
  patch '/history/movie/update_dislike/:id', to: 'saved_movies#history_update_dislike', as: 'history_update_dislike' # change rating button SHOW (dislike)
  patch '/history/movie/update_index/:id', to: 'saved_movies#history_update_index', as: 'history_update_index' # change rating button INDEX
  get '/history/movie/:id', to: 'saved_movies#history_show', as: 'history_show'  # history show page
  delete '/history/movie/:id', to: 'saved_movies#history_destroy', as: 'history_destroy' # remove button

  # routes related to 'Avatar' button in navbar
  get '/user/:id', to: 'user#show' # profile page that you open when you click on the avatar
    # other routes (e.g. update) are already present thanks to devise. USE THEM!!

  # routes related to 'Saved' button in navbar
  get '/saved', to: 'saved_movies#saved_show', as: "saved_movie" # saved show page, only one movie is show
  get '/saved/pass', to: 'saved_movies#saved_pass', as: "pass_saved_movie"
  get '/saved/remove', to: 'saved_movies#saved_destroy', as: "remove_saved_movie" # remove button

  # routes related to 'Watch now' button in navbar
  get '/search', to: 'suggestions#home'

  # [KK - 23 Apr] removed the /:id from URI - will not be needed for our logic
  get '/results', to: 'suggestions#show'

  get '/results/pass', to: 'suggestions#pass_suggestion', as: 'pass_suggestion'
  get '/results/later', to: 'suggestions#move_to_later', as: 'move_to_later'
  get '/results/seen', to: 'suggestions#already_seen', as: 'already_seen'

  # pass, later and seen buttons won't trigger a new route, they will trigger only different methods that will
  # be activated based on the JS button listener. These methods will be created in the suggestions controller
  get '/pages/home', to: 'pages#home', as: 'home'
  get '/pages/:movie_id/confirmation', to: 'pages#confirmation', as: 'confirmation'
  get '/pages/after_confirmation', to: 'pages#after_confirmation', as: 'after_confirmation'
end

app/controllers/saved_movies_controller.rb
class SavedMoviesController < ApplicationController
  def saved_show
    @current_saved_movie = []
    @second_saved_movie = []
    @saved_movies = current_user.saved_movies.where(seen: false)

    @render_static_page = false
    @multiple_cards = true
    @multiple_movies = true

    if @saved_movies.size == 0
      @render_static_page = true
    elsif @saved_movies.size == 1
      @current_saved_movie << @saved_movies.first
      @multiple_movies = false
    else
      counter = 0;
      @saved_movies.each do |saved_movie|
        if saved_movie.skip == false && counter == 0
          @current_saved_movie << saved_movie
          counter += 1
        elsif saved_movie.skip == false && counter == 1
          @second_saved_movie << saved_movie
          counter = 0
          break
        end
      end

      if @second_saved_movie == []
        @second_saved_movie = [@saved_movies.second]
      end

      # this loop resets the situation when we reached the last suggestions
      if @current_saved_movie == []
        @current_saved_movie << @saved_movies.first
        @saved_movies.each do |saved_movie|
          saved_movie.update(skip: false)
        end
      end
    end
  end

  def saved_destroy
    SavedMovie.find(params[:id]).destroy
    redirect_to saved_movie_path
  end

  def saved_pass
    SavedMovie.find(params[:id]).update(skip: true)
    redirect_to saved_movie_path
  end

  def saved_watch
    redirect_to watch_confirmation_path(movie_id: SavedMovie.find(params[:id]).movie.id)
  end

  def history_index
    @seen_movies = current_user.saved_movies.where(seen: true).order(created_at: :desc)
    # @current_movie = [@seen_movies.each do find(:id)]
    # @rating = rating_icon

  end

  def history_show
    @current_movie = [SavedMovie.find(params[:id])] #needs to be an array
    # @current_movie = Movie.find(params[:id]) #not an object
    @current_rating = @current_movie.first.user_rating

    @rating = rating_icon
    # @rating_dislike = rating_icon_dislike
  end

  def rating_icon
    if @current_rating == 1
      return "icons/disliked_hover.svg"
    else
      return "icons/liked_hover.svg"
    end
  end

  def history_update
    @saved_movie = SavedMovie.find(params[:id])
    @saved_movie.user_rating == 1 ? @saved_movie.update(user_rating: 0) : @saved_movie.update(user_rating: 1)
    redirect_to history_show_path(@saved_movie)
  end

  def history_update_like
    @saved_movie = SavedMovie.find(params[:id])
    @saved_movie.update(user_rating: 1)
    redirect_to history_show_path(@saved_movie)
  end

  def history_update_dislike
    @saved_movie = SavedMovie.find(params[:id])
    @saved_movie.update(user_rating: 0)
    redirect_to history_show_path(@saved_movie)
  end

  def history_update_index
    @saved_movie = SavedMovie.find(params[:id])
    @saved_movie.user_rating == 1 ? @saved_movie.update(user_rating: 0) : @saved_movie.update(user_rating: 1)
    redirect_to history_index_path
  end

  def history_destroy
    SavedMovie.find(params[:id]).destroy
    redirect_to history_index_path
  end
end

app/views/saved_movies/history_index.html.erb
<div class="row history-container">
  <% @seen_movies.each do |saved_movie| %>
    <div class="col-3 movie-card-opacity-animation">
    <div class="thumbs-up-badge">
          <% if saved_movie.user_rating == 1 %>
          <div class="img-responsive badge-icon-index action-button">
          <%= link_to (image_tag "icons/liked_hover.svg"), history_update_index_path(id: saved_movie.id), method: :patch %>
          </div>
          <% elsif saved_movie.user_rating == 0 %>
          <div class="img-responsive badge-icon-index action-button">
          <%= link_to (image_tag "icons/disliked_hover.svg"), history_update_index_path(id: saved_movie.id), method: :patch %>
          </div>
          <% else %>
          <%= tag.div class: %w( img-responsive badge-icon-index whatch-badge-icon-empty ) %>
          <% end %>
        </div>     
        
      <div class="movie-poster-small">
        <% if saved_movie.movie.photo_url == nil%>
        <%= link_to history_show_path(saved_movie.id) do %>
        <div class="movie-poster-placeholder">
        <%= tag.h3 "#{saved_movie.movie.title}" %>
        <% end %>
        </div>
        <% else %>
        <%= link_to history_show_path(saved_movie.id) do %>
        <%= image_tag ("https://image.tmdb.org/t/p/w200/#{saved_movie.movie.photo_url}"), class: "img-responsive movie-poster-image"%>
        <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/saved_movies/history_show.html.erb
<!-- render partial with the result show -->
<!-- define locals used in partial -->
<% if @current_rating == nil %>
  <%= render layout:"layouts/result_show", locals: {
    queried_actors: [],
    queried_directors: [],
    queried_genres: [],

    current_suggestion: @current_movie,
    movie_director: @current_movie[0].movie.director,
    starring_actors: @current_movie[0].movie.starring_actors,

    # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
    # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
    number_of_buttons: 3,
    multiple_cards: false,

    first_button_path: history_destroy_path(id: @current_movie.first.id), remote:true,
    first_button_image: "icons/pass_action.svg",
    first_button_class: "history-remove-action",
    first_button_label: "remove",
    first_button_method: :delete,

    second_button_path: history_update_dislike_path(id: @current_movie.first.id),
    second_button_image: "icons/disliked_neutral.svg",
    second_button_class: "history-change-rating-action",
    second_button_label: "dislike",
    second_button_method: :patch,

    third_button_path: history_update_like_path(id: @current_movie.first.id),
    third_button_image: "icons/liked_neutral.svg",
    third_button_class: "history-change-rating-action",
    third_button_label: "like",
    third_button_method: :patch

    } do %>
  <% end %>
<% else %>
  <%= render layout:"layouts/result_show", locals: {
    queried_actors: [],
    queried_directors: [],
    queried_genres: [],

    current_suggestion: @current_movie,
    movie_director: @current_movie[0].movie.director,
    starring_actors: @current_movie[0].movie.starring_actors,

    # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
    # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
    number_of_buttons: 2,
    multiple_cards: false,

    first_button_path: history_destroy_path(id: @current_movie.first.id), remote:true,
    first_button_image: "icons/pass_action.svg",
    first_button_class: "history-remove-action",
    first_button_label: "remove",
    first_button_method: :delete,

    second_button_path: history_update_path(id: @current_movie.first.id),
    second_button_image: @rating, #"icons/disliked.svg",
    second_button_class: "history-change-rating-action",
    second_button_label: "rate",
    second_button_method: :patch

    } do %>
  <% end %>
<% end %>

app/views/saved_movies/saved_show.html.erb
<% @multiple_cards = false if @second_saved_movie == [] %>

<% if @render_static_page %>
<div class="no-saved-movies">
  <h1>you have no saved movies yet</h1>
    <div class="no-saved-movies-icon">
      <%= link_to root_path do %>
      <%= image_tag ("filter_icons/search.png") %>
      <% end %>
    </div>
  </div>
<% elsif @multiple_movies %>

  <%= render layout:"layouts/result_show", locals: {
    queried_actors: [],
    queried_directors: [],
    queried_genres: [],

    current_suggestion: @current_saved_movie,
    second_suggestion: @second_saved_movie,
    movie_director: @current_saved_movie.first.movie.director,
    starring_actors: @current_saved_movie.first.movie.starring_actors,

    # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
    # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
    number_of_buttons: 3,
    multiple_cards: @multiple_cards,

    first_button_path: remove_saved_movie_path(id: @current_saved_movie.first.id), remote:true,
    first_button_image: "icons/pass_action.svg",
    first_button_class: "pass-action",
    first_button_label: "remove",
    first_button_method: :get,

    second_button_path: pass_saved_movie_path(id: @current_saved_movie.first.id), remote: true,
    second_button_image: "icons/next_action.svg",
    second_button_class: "next-action",
    second_button_label: "next",
    second_button_method: :get,

    third_button_path: confirmation_path(movie_id: @current_saved_movie.first.movie_id), remote: true,
    third_button_image: "icons/watch_action.svg",
    third_button_class: "watch_action",
    third_button_label: "watch",
    third_button_method: :get,
    } do %>
  <% end %>

<% else %>
  <%= render layout:"layouts/result_show", locals: {
    queried_actors: [],
    queried_directors: [],
    queried_genres: [],

    current_suggestion: @current_saved_movie,
    movie_director: @current_saved_movie.first.movie.director,
    starring_actors: @current_saved_movie.first.movie.starring_actors,

    # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
    # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
    number_of_buttons: 2,
    multiple_cards: @multiple_cards,

    first_button_path: remove_saved_movie_path(id: @current_saved_movie.first.id), remote:true,
    first_button_image: "icons/pass_action.svg",
    first_button_class: "pass-action",
    first_button_label: "remove",
    first_button_method: :get,

    second_button_path: confirmation_path(movie_id: @current_saved_movie.first.movie_id), remote: true,
    second_button_image: "icons/watch_action.svg",
    second_button_class: "watch_action",
    second_button_label: "watch",
    second_button_method: :get,
    } do %>
  <% end %>

<% end %>