config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Sidekiq Web UI, only for admins.
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # home route
  root to: 'pages#landing'

  get '/profile', to: 'pages#profile'

  # TMDB suggestions route after user selection of filters
  get '/tmdb_suggestions/:params', to: 'tmdb_suggestions#fetcher'

  # route to achievements
  get '/achievements', to: 'achievements#index'

  # routes related to 'History' button in navbar
  get '/history', to: 'saved_movies#history_index', as: 'history_index' #history index
  patch '/history/movie/update/:id', to: 'saved_movies#history_update', as: 'history_update' # change rating button SHOW (switch)
  patch '/history/movie/update_like/:id', to: 'saved_movies#history_update_like', as: 'history_update_like' # change rating button SHOW (like)
  patch '/history/movie/update_dislike/:id', to: 'saved_movies#history_update_dislike', as: 'history_update_dislike' # change rating button SHOW (dislike)
  patch '/history/movie/update_index/:id', to: 'saved_movies#history_update_index', as: 'history_update_index' # change rating button INDEX
  get '/history/movie/:id', to: 'saved_movies#history_show', as: 'history_show'  # history show page
  delete '/history/movie/:id', to: 'saved_movies#history_destroy', as: 'history_destroy' # remove button

  # routes related to 'Avatar' button in navbar
  get '/user/:id', to: 'user#show' # profile page that you open when you click on the avatar
    # other routes (e.g. update) are already present thanks to devise. USE THEM!!

  # routes related to 'Saved' button in navbar
  get '/saved', to: 'saved_movies#saved_show', as: "saved_movie" # saved show page, only one movie is show
  get '/saved/pass', to: 'saved_movies#saved_pass', as: "pass_saved_movie"
  get '/saved/remove', to: 'saved_movies#saved_destroy', as: "remove_saved_movie" # remove button

  # routes related to 'Watch now' button in navbar
  get '/search', to: 'suggestions#home'

  # [KK - 23 Apr] removed the /:id from URI - will not be needed for our logic
  get '/results', to: 'suggestions#show'

  get '/results/pass', to: 'suggestions#pass_suggestion', as: 'pass_suggestion'
  get '/results/later', to: 'suggestions#move_to_later', as: 'move_to_later'
  get '/results/seen', to: 'suggestions#already_seen', as: 'already_seen'

  # pass, later and seen buttons won't trigger a new route, they will trigger only different methods that will
  # be activated based on the JS button listener. These methods will be created in the suggestions controller
  get '/pages/home', to: 'pages#home', as: 'home'
  get '/pages/:movie_id/confirmation', to: 'pages#confirmation', as: 'confirmation'
  get '/pages/after_confirmation', to: 'pages#after_confirmation', as: 'after_confirmation'
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :movie
  belongs_to :tmdb_suggestion
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  # calls method to set suggestion.skip to true, if user clicks on the pass, later, or seen button in show
  before_action :set_suggestion_skip, only: [ :pass_suggestion ]

  def show
    # the show accepts a parameter from the filters page
    # the @tmdb_suggestion declaration is temporary, until we successfully receive sample tmdb_suggestions
    @query = current_user.queries.last
    @current_suggestion = []
    @second_suggestion = []
    @tmdb_suggestion = current_user.tmdb_suggestions.last.suggestions
    counter = 0;

    @tmdb_suggestion.each do |suggestion|
      if suggestion.skip == false && counter == 0
        @current_suggestion << suggestion
        counter += 1
      elsif suggestion.skip == false && counter == 1
        @second_suggestion << suggestion
        counter = 0
        break
      end
    end

    # this loop resets the situation when we reached the last suggestions
    if @current_suggestion == []
      @current_suggestion << @tmdb_suggestion.first
      @tmdb_suggestion.each do |suggestion|
        suggestion.update(skip: false)
      end
      @second_suggestion << @tmdb_suggestion.second
    end
  end

  # controller methods for pass, later, seen buttons in show
  # TODO: each method must be updated with the necessary function(s) for each button action
  def pass_suggestion
    redirect_to results_path
  end

  def move_to_later
    suggestion = Suggestion.find(params[:suggestion_id])
    SavedMovie.create(user: current_user, movie: suggestion.movie)
    suggestion.destroy
    redirect_to results_path
  end

  def already_seen
    suggestion = Suggestion.find(params[:suggestion_id])
    SavedMovie.create(user: current_user, movie: suggestion.movie, seen: true)
    suggestion.destroy
    redirect_to results_path
  end

  def confirmation
    @current_suggestion = []
    @current_suggestion << Suggestion.find(params[:id])
  end

  # def destroy
  #   @suggestion = Suggestion.find(params[:id])
  #   @suggestion.update(skip: true)
  #   redirect_to_pages_suggestions_path
  # end


  private

  def suggestion_params
    params.require(:suggestion).permit( :tmdb_suggestion_id, :movie_id, :skip)
  end


  # method to set current suggestion.skip displayed in show to true, then present next suggestion to show
  def set_suggestion_skip
    @suggestion = Suggestion.find(params[:suggestion_id])
    @suggestion.update(skip: true)
  end

  def route_back_to_page
    redirect_to results_path
  end

end

app/views/suggestions/show.html.erb
<!-- render partial with the result show -->
<!-- define locals used in partial -->
<% if @current_suggestion == [nil] || @current_suggestion == [] %>
  <div class="no-saved-movies">
  <h1>You have finished your suggestions!</h1>
  <h2>try again?</h2>
    <div class="no-saved-movies-icon">
      <%= link_to home_path do %>
      <%= image_tag ("logo_white.png") %>
      <% end %>
    </div>
  </div>
<% else %>

  <% queried_actors = [] %>
  <% queried_genres = [] %>
  <% queried_directors = [] %>

  <% if @query %>
    <% @query.positive_actors_tmdb_ids.each do |actor_tmdb_id| %>
      <% queried_actors << Actor.find_by(tmdb_id: actor_tmdb_id) %>
    <% end %>

    <% @query.positive_directors_tmdb_ids.each do |director_tmdb_id| %>
      <% queried_directors << Director.find_by(tmdb_id: director_tmdb_id) %>
    <% end %>

    <% @query.positive_genres_tmdb_ids.each do |genre_tmdb_id| %>
      <% queried_genres << Genre.find_by(tmdb_id: genre_tmdb_id) %>
    <% end %>
  <% end %>


  <% multiple_cards = ((@second_suggestion == [] || @second_suggestion == [nil]) ? false : true) %>

  <%= render layout:"layouts/result_show", locals: {
    queried_actors: queried_actors,
    queried_directors: queried_directors,
    queried_genres: queried_genres,

    current_suggestion: @current_suggestion,
    second_suggestion: @second_suggestion,
    movie_director: @current_suggestion.first.movie.director,
    starring_actors: @current_suggestion.first.movie.starring_actors,

    # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
    # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
    number_of_buttons: 4,
    multiple_cards: multiple_cards,

    first_button_path: pass_suggestion_path(suggestion_id: @current_suggestion.first.id),
    first_button_image: "icons/pass_action.svg",
    first_button_class: "pass-action",
    first_button_label: "pass",
    first_button_method: :get,

    second_button_path: already_seen_path(suggestion_id: @current_suggestion.first.id),
    second_button_image: "icons/seen_action.svg",
    second_button_class: "seen-action",
    second_button_label: "seen",
    second_button_method: :get,

    third_button_path: move_to_later_path(suggestion_id: @current_suggestion.first.id),
    third_button_image: "icons/save_action.svg",
    third_button_class: "save-action",
    third_button_label: "save",
    third_button_method: :get,

    fourth_button_path: confirmation_path(movie_id: @current_suggestion.first.movie_id),
    fourth_button_image: "icons/watch_action.svg",
    fourth_button_class: "watch_action",
    fourth_button_label: "watch",
    fourth_button_method: :get,
    } do %>
  <% end %>

<% end %>

app/views/suggestions/suggestion_show.html.erb
 <div class=container>
  <div class="poster-card">
    <% @current_suggestion = @suggestions.find(params[:id]) %>
    <% # raise %>
    <% next_id = find_next_id(@current_suggestion) %>

    <% suggested_movie = @current_suggestion.movie %>
    <% movie_director = suggested_movie.director %>
    <% starring_actors = suggested_movie.starring_actors %>
    <% available_services = suggested_movie.available_services %>
    <h2><%= suggested_movie.title %></h3>
    <p><%= suggested_movie.release_date %></p>
    <p><%= suggested_movie.runtime %> minutes</p>
    <p><%= suggested_movie.overview %></p>
    <h3>Starring Actors:</h3>
    <h3>Director: </h3>
    <p><%= movie_director.name %></p>
    <h3>Available on: </h3>
    <% available_services.each do |service| %>
      <p><%= Service.find(service.service_id).company %></p>
    <% end %>
  </div>
  <br>
  <div class="buttons">
    <%= link_to "Pass", show_suggestions_path(next_id) %>
    <%= link_to "Later", show_suggestions_path(next_id) %>
    <%= link_to "Seen", show_suggestions_path(next_id) %>
    <%= link_to "Watch", "/suggestion/#{@current_suggestion.id}/confirmation" %>
  </div>
</div>