config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Sidekiq Web UI, only for admins.
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # home route
  root to: 'pages#landing'

  get '/profile', to: 'pages#profile'

  # TMDB suggestions route after user selection of filters
  get '/tmdb_suggestions/:params', to: 'tmdb_suggestions#fetcher'

  # route to achievements
  get '/achievements', to: 'achievements#index'

  # routes related to 'History' button in navbar
  get '/history', to: 'saved_movies#history_index', as: 'history_index' #history index
  patch '/history/movie/update/:id', to: 'saved_movies#history_update', as: 'history_update' # change rating button SHOW (switch)
  patch '/history/movie/update_like/:id', to: 'saved_movies#history_update_like', as: 'history_update_like' # change rating button SHOW (like)
  patch '/history/movie/update_dislike/:id', to: 'saved_movies#history_update_dislike', as: 'history_update_dislike' # change rating button SHOW (dislike)
  patch '/history/movie/update_index/:id', to: 'saved_movies#history_update_index', as: 'history_update_index' # change rating button INDEX
  get '/history/movie/:id', to: 'saved_movies#history_show', as: 'history_show'  # history show page
  delete '/history/movie/:id', to: 'saved_movies#history_destroy', as: 'history_destroy' # remove button

  # routes related to 'Avatar' button in navbar
  get '/user/:id', to: 'user#show' # profile page that you open when you click on the avatar
    # other routes (e.g. update) are already present thanks to devise. USE THEM!!

  # routes related to 'Saved' button in navbar
  get '/saved', to: 'saved_movies#saved_show', as: "saved_movie" # saved show page, only one movie is show
  get '/saved/pass', to: 'saved_movies#saved_pass', as: "pass_saved_movie"
  get '/saved/remove', to: 'saved_movies#saved_destroy', as: "remove_saved_movie" # remove button

  # routes related to 'Watch now' button in navbar
  get '/search', to: 'suggestions#home'

  # [KK - 23 Apr] removed the /:id from URI - will not be needed for our logic
  get '/results', to: 'suggestions#show'

  get '/results/pass', to: 'suggestions#pass_suggestion', as: 'pass_suggestion'
  get '/results/later', to: 'suggestions#move_to_later', as: 'move_to_later'
  get '/results/seen', to: 'suggestions#already_seen', as: 'already_seen'

  # pass, later and seen buttons won't trigger a new route, they will trigger only different methods that will
  # be activated based on the JS button listener. These methods will be created in the suggestions controller
  get '/pages/home', to: 'pages#home', as: 'home'
  get '/pages/:movie_id/confirmation', to: 'pages#confirmation', as: 'confirmation'
  get '/pages/after_confirmation', to: 'pages#after_confirmation', as: 'after_confirmation'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  has_many :joint_achievements
  has_many :users, through: :joint_achievements


  has_one_attached :photo
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :awards, as: :awardable

  has_many :starring_actors
  has_many :movies, through: :starring_actors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_service.rb
class AvailableService < ApplicationRecord
  belongs_to :movie
  belongs_to :service
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :awardable, polymorphic: true
  belongs_to :movie
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :movies
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :awards, as: :awardable
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :joint_genres
  has_many :movies, through: :joint_genres

  has_one_attached :photo
end

app/models/joint_achievement.rb
class JointAchievement < ApplicationRecord
  belongs_to :user
  belongs_to :achievement
end

app/models/joint_genre.rb
class JointGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director, optional: true
  belongs_to :collection, optional: true

  has_many :awards

  has_many :saved_movies
  has_many :users, through: :saved_movies

  has_many :joint_genres
  has_many :genres, through: :joint_genres

  has_many :starring_actors
  has_many :actors, through: :starring_actors

  has_many :available_services
  has_many :services, through: :available_services
end

app/models/query.rb
class Query < ApplicationRecord
  belongs_to :user
  has_one :tmdb_suggestion
end

app/models/saved_movie.rb
class SavedMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :available_services
  has_many :movies, through: :available_services

  has_one_attached :photo
end

app/models/starring_actor.rb
class StarringActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :movie
  belongs_to :tmdb_suggestion
end

app/models/tmdb_suggestion.rb
class TmdbSuggestion < ApplicationRecord
  belongs_to :user
  belongs_to :query

  has_many :suggestions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :queries

  has_many :saved_movies
  has_many :movies, through: :saved_movies

  has_many :tmdb_suggestions
  has_many :suggestions, through: :tmdb_suggestions

  has_one_attached :photo

  has_many :joint_achievements
  has_many :achievements, through: :joint_achievements
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/_result_show.html.erb
<!-- every page that renders this result_show partial needs to include the locals on the bottom of this page -->
<!-- example: current_suggestion = @current_suggestion (if @current_suggestion is passed on from controller) -->
<!-- SCROLL DOWN FOR DETAILS -->
<% if number_of_buttons <= 2 %>
  <% result_actions = "two-buttons" %>
<% elsif number_of_buttons == 3 %>
  <% result_actions = "three-buttons" %>
<% else %>
  <% result_actions = "four-buttons" %>
<% end %>

<div class="result-container">

  <div class="result-left">
    <div class="result-cards">
      <!-- logic for handling multiple cards -->
      <% if multiple_cards == true %>
        <div class="first-result normal-result">
          <% if current_suggestion.first.movie.photo_url.nil? %>
            <%= image_tag "poster_placeholder.png" %>
          <% else %>
            <%= image_tag "https://image.tmdb.org/t/p/w300/#{current_suggestion.first.movie.photo_url}" %>
          <% end %>
            <% unless current_suggestion.first.movie.trailer_url.nil? %>
            <span style="cursor: pointer;" id="trailer-button" class="play-button"><i class="far fa-play-circle"></i></span>
          <% end %>
        </div>
        <div class="second-result">
          <!-- TODO: image path below must be updated with the second suggestion -->
          <% if !second_suggestion.first.movie.photo_url.nil? %>
            <%= image_tag "https://image.tmdb.org/t/p/w300/#{second_suggestion.first.movie.photo_url}" %>
          <% else %>
            <%= image_tag "poster_placeholder.png" %>
          <% end %>
        </div>
      <!-- logic for handling one card WITH buttons -->
      <% elsif multiple_cards == false && number_of_buttons > 0 %>
        <div class="single-result">
          <div class="movie-poster-container normal-result">
            <div class="small-rating-badge">
              <% unless current_suggestion.first.class.to_s == 'Suggestion' %>
                <% if current_suggestion.first.user_rating == 1 %>
                  <%= tag.div class: %w( img-responsive badge-icon whatch-badge-icon-like ) %>
                <% elsif current_suggestion.first.user_rating == 0 %>
                  <%= tag.div class: %w( img-responsive badge-icon whatch-badge-icon-dislike ) %>
                <% else %>
                  <%= tag.div class: %w( img-responsive badge-icon whatch-badge-icon-empty ) %>
                <% end %>
              <% end %>
            </div>
            <% if !current_suggestion.first.movie.photo_url.nil? %>
              <%= image_tag "https://image.tmdb.org/t/p/w300/#{current_suggestion.first.movie.photo_url}" %>
            <% else %>
              <%= image_tag "poster_placeholder.png" %>
            <% end %>
            <% unless current_suggestion.first.movie.trailer_url.nil? %>
              <span style="cursor: pointer;" id="trailer-button" class="play-button"><i class="far fa-play-circle"></i></span>
            <% end %>
          </div>
        </div>
      <!-- logic for handling one card WITHOUT buttons -->
      <% else %>
        <div class="single-result poster-large normal-result">
          <% if !current_suggestion.first.movie.photo_url.nil? %>
            <%= image_tag "https://image.tmdb.org/t/p/w300/#{current_suggestion.first.movie.photo_url}" %>
          <% else %>
            <%= image_tag "poster_placeholder.png" %>
          <% end %>
          <% unless current_suggestion.first.movie.trailer_url.nil? %>
            <span style="cursor: pointer;" id="trailer-button" class="play-button"><i class="far fa-play-circle"></i></span>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- Creates dynamic left/right padding based on number of buttons to display -->
    <% if number_of_buttons > 0 %>
      <div class="result-actions <%= result_actions %>">
        <div class="action-button">
          <%= link_to (image_tag first_button_image, size: 48), first_button_path, method: first_button_method, class:first_button_class %>
          <div class="action-label">
            <p><%= first_button_label %></p>
          </div>
        </div>
        <div class="action-button">
          <%= link_to (image_tag second_button_image, size: 48), second_button_path, method: second_button_method, class:second_button_class %>
          <div class="action-label">
            <p><%= second_button_label %></p>
          </div>
        </div>
        <!-- Displays 3 buttons only if number_of_buttons is specified as such by the show -->
        <% if number_of_buttons >= 3 %>
          <div class="action-button">
            <%= link_to (image_tag third_button_image, size: 48), third_button_path, method: third_button_method, class:third_button_class %>
            <div class="action-label">
              <p><%= third_button_label %></p>
            </div>
          </div>
        <% end %>
        <!-- Displays 4 buttons only if number_of_buttons is specified as such by the show -->
        <% if number_of_buttons == 4 %>
          <div class="action-button">
            <%= link_to (image_tag fourth_button_image, size: 48), fourth_button_path, method: fourth_button_method, class:fourth_button_class %>
            <div class="action-label">
              <p><%= fourth_button_label %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="result-right">
    <div class="result-right-top">
    </div>

    <!-- movie details for results confirmation page only -->
    <% if multiple_cards == false && number_of_buttons == 0 %>
      <div class="result-right-main confirmation">
        <div class="confirmation-details">
          <div class="confirmation-header">
            <h1>
              <%= @current_suggestion.first.movie.title %>
            </h1>
            <h2>
              <%= Time.now.strftime("%A %d %b %Y") %>
              <br>
              <%= Time.now.strftime("%H.%M") %>
            </h2>
          </div>
          <div class="confirmation-message">
            <p>Sit back, relax, and enjoy <%= @current_suggestion.first.movie.title %>!</p>
            <p>When you're done with the movie, you can go to the History tab to give it a thumbs up or thumbs down.</p>
            <br>

              <% if @current_suggestion.first.movie.available_services == [] %>
                <%= link_to "Watch now", after_confirmation_path(movie_id: @current_suggestion.first.movie_id), class:"button-full" %>
              <% else %>

                <h2 style="opacity: 1; color: #239F94; font-size: 14px; font-weight: 600;">Watch now on:</h2>
                <div id="services-container">
                  <% @current_suggestion.first.movie.available_services.each do |available_service| %>
                    <%= link_to (image_tag available_service.service.icon), after_confirmation_path(movie_id: @current_suggestion.first.movie_id), class: 'service-card', data: { link: available_service.url} %>
                  <% end %>
                </div>

              <% end %>

          </div>
        </div>
        <div class="confirmation-admit-one">

        </div>
      </div>
      <!-- code goes here -->
    <!-- movie details for all pages that are not the results confirmation page -->
    <% else %>
      <div class="result-right-main">
        <div class="film-header">
          <h1>
            <%= current_suggestion.first.movie.title %>
          </h1>
          <p>
            <%= current_suggestion.first.movie.overview %>
          </p>
        </div>
        <div class="film-details">
          <div class="film-details-item">
            <h2>
              Director
            </h2>

            <% if queried_directors.include?(movie_director) %>
              <p class="positive-query-text"><%= movie_director.name %></p>
            <% else %>
              <p><%= movie_director.name %></p>
            <% end %>

          </div>
          <div class="film-details-item">

            <h2>
              Genre
            </h2>
              <!-- Iterate over genre -->
              <div style="display: flex;">
                <% counter = 0 %>
                <% current_suggestion.first.movie.genres.uniq.each do |genre| %>
                  <% counter += 1 %>

                  <% unless counter == 1 %>
                    <p>,&nbsp;</p>
                  <% end %>

                  <% if queried_genres.include?(genre) %>
                    <p class="positive-query-text"><%= genre.name %></p>
                  <% else %>
                    <p><%= genre.name %></p>
                  <% end %>
                <% end %>

              </div>

          </div>

          <div class="film-details-item">
            <h2>
              Released
            </h2>
            <p>
              <%= current_suggestion.first.movie.release_date.split("-").first %>
            </p>
          </div>
          <div class="film-details-item">
            <h2>
              Runtime
            </h2>
            <p>
              <%= current_suggestion.first.movie.runtime %> min
            </p>
          </div>
        </div>

        <h2>Cast</h2>
        <div class="film-cast">

          <% starring_actors.take(15).each do |starring_actor| %>
            <% cast_icon = (queried_actors.include?(starring_actor.actor) ? "cast-icon queried" : cast_icon = "cast-icon") %>
            <div class="cast-member">
              <div class="cast-centered">
                <% if starring_actor.photo_url != nil %>
                  <%= image_tag("https://image.tmdb.org/t/p/w500#{starring_actor.photo_url}", size: 48, class: cast_icon) %>
                <% elsif starring_actor.actor.photo_url != nil %>
                  <%= image_tag("https://image.tmdb.org/t/p/w500#{starring_actor.actor.photo_url}", size: 48, class: cast_icon) %>
                <% else %>
                  <%= image_tag("icons/placeholder_actor.svg", size: 48, class: cast_icon) %>
                <% end %>
                <p>
                  <% actor_name = starring_actor.actor.name %>
                  <!-- If actor is known by just one name, print the name as-is -->
                  <% if actor_name.index(" ").nil? %>
                    <%= actor_name %>
                  <!-- if the user has more than two names, fit as much as possible (10 chars) on the first line before the line break -->
                  <% elsif actor_name.count(" ") >= 2 && actor_name.split(" ")[0].length + actor_name.split(" ")[1].length <= 10 %>
                    <%= actor_name.split(" ")[0] + " " + actor_name.split(" ")[1] %>
                    <br>
                    <%= actor_name.slice(actor_name.split(" ")[0].length + actor_name.split(" ")[1].length + 2..actor_name.length) %>
                  <!-- in all other circumstances, print the first name, then a line break, then last name -->
                  <% else %>
                    <%= actor_name.split(" ").first %>
                    <br>
                    <%= actor_name.slice(actor_name.index(" ") + 1..actor_name.length) %>
                  <% end %>
                </p>
              </div>
            </div>
          <% end %>

        </div>


      </div>
      <% end %>
    <div class="result-right-bottom">
    </div>
  </div> <!-- close result-right -->
</div>


<div id="transparent-background"> <!-- CSS in /container.scss -->
  <div class="modal-container">
    <div class="video-x"> <!-- in order to position the x -->
      <% unless current_suggestion.first.movie.trailer_url.nil? %>
        <iframe enablejsapi="1" src=<%= current_suggestion.first.movie.trailer_url.gsub("watch?v=", "embed/") %>></iframe>
      <% end %>
      <span style="cursor: pointer;" id="x-button"><i class="far fa-times-circle fa-circle"></i></span>
    </div>
  </div>
</div>



<!-- include the following locals in your code if you use this partial -->

<!-- NOTE: if number_of_buttons is 2, you can remove all lines starting with 'third_button' and 'fourth_button' -->
<!--       if your number_of_buttons is 3, you can remove all lines starting with 'third_button' -->

<!-- IMPORTANT: if YOUR_INPUT_HERE is surrounded by quotes, you must include them in your local -->
<!--            input for the button_method must be a symbol (e.g., :get) -->
<!--            even if your link method is 'get', you MUST specify :get for the partial to work -->

<!--

  current_suggestion: @current_suggestion,
  second_suggestion: @second_suggestion,
  movie_director: @current_suggestion.first.movie.director,
  starring_actors: @current_suggestion.first.movie.starring_actors,


  # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
  # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"

  number_of_buttons: YOUR_INPUT_HERE,
  multiple_cards: YOUR_INPUT_HERE,

  first_button_path: YOUR_INPUT_HERE,
  first_button_image: "YOUR_INPUT_HERE",
  first_button_class: "YOUR_INPUT_HERE",
  first_button_label: "YOUR_INPUT_HERE",
  first_button_method: YOUR_INPUT HERE

  second_button_path: YOUR_INPUT_HERE,
  second_button_image: "YOUR_INPUT_HERE",
  second_button_class: "YOUR_INPUT_HERE",
  second_button_label: "YOUR_INPUT_HERE",

  third_button_path: YOUR_INPUT_HERE,
  third_button_image: "YOUR_INPUT_HERE",
  third_button_class: "YOUR_INPUT_HERE",
  third_button_label: "YOUR_INPUT_HERE",

  fourth_button_path: YOUR_INPUT_HERE,
  fourth_button_image: "YOUR_INPUT_HERE",
  fourth_button_class: "YOUR_INPUT_HERE",
  fourth_button_label: "YOUR_INPUT_HERE"

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= meta_title %>">
  <meta name="twitter:description" content="<%= meta_description %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= meta_image %>">

    <!-- <title>Whatch - Whatch helps you choose your next movie without effort! Let WHATCH do the heavy-lifting: sit back and watch your next favorite movie!</title> -->
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag %>
  </head>
  <% if current_page?("/") %>
    <body id="landing-body">
  <% else %>
    <body>
  <% end %>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>

      <%= render 'shared/footer' %>
      <%= javascript_pack_tag 'application' %>
    </body>
</html>

app/views/pages/confirmation.html.erb
<%= render layout:"layouts/result_show", locals: {
  queried_actors: [],
  queried_directors: [],
  queried_genres: [],

  current_suggestion: @current_suggestion,
  movie_director: @current_suggestion.first.movie.director,
  starring_actors: @current_suggestion.first.movie.starring_actors,

  # NOTE: if the number_of_buttons you specify is 2 or 3, you can delete the lines for buttons you don't need
  # e.g., if you need only two buttons, you can delete all lines that start with "third_button" and "fourth_button"
  number_of_buttons: 0,
  multiple_cards: false
  } do %>
<% end %>

app/views/pages/profile.html.erb
<!-- navbar -->

<div class="profile-container"> <!-- in /_container.scss -->
  <%= link_to "Edit profile", edit_user_registration_path, class: "button-full" %>
  <div class="cards-container"> <!-- in /_container.scss -->
    <div class="profile-card"> <!-- in /_card.scss -->
      <h2>FIRST NAME</h2>
      <p><%= current_user.first_name %></p>
    </div>
    <div class="profile-card">
      <h2>LAST NAME</h2>
      <p><%= current_user.last_name %></p>
    </div>
    <div class="profile-card">
      <h2>COUNTRY</h2>
      <p><%= current_user.country%></p>
    </div>
    <div class="profile-card">
      <h2>EMAIL ADDRESS</h2>
      <p><%= current_user.email %></p>
    </div>
  </div> <!-- end of div.cards-container -->
  <%= link_to "Log Out", destroy_user_session_path, class: "button-full", method: :delete %>
</div> <!-- end of divprofile-container  -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>This product uses the TMDb API but is not endorsed or certified by&nbsp;</p>
  <%= image_tag "tmdb_logo.svg" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-whatch">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_white.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <!-- this stores the current relative url for highlighting the navbar buttons accordingly -->
  <% current_url = request.fullpath %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav nav-pills">
      <% if user_signed_in? %>
        <li class="nav-item whatch-nav-item">
          <% if current_page?("/pages/home") || current_page?("/results") || current_page?("/pages") %>
          <%= link_to "Watch Now", "/pages/home", class: "whatch-nav-link whatch-nav-item-active" %>
          <% else %>
          <%= link_to "Watch Now", "/pages/home", class: "whatch-nav-link" %>
          <% end %>
        </li>
        <li class="nav-item whatch-nav-item">
          <!-- the method below is currently working for highlighting the current view on the history navbar buttons -->
          <% if current_url.include?("/history")%>
          <%= link_to "History", "/history", class: "whatch-nav-link whatch-nav-item-active" %>
          <% elsif  current_url.include?("/history/movie/#{Integer}")%>
          <%= link_to "History", "/history", class: "whatch-nav-link whatch-nav-item-active" %>
          <% else %>
          <%= link_to "History", "/history", class: "whatch-nav-link" %>
          <% end %>
        </li>
        <li class="nav-item whatch-nav-item">
          <% if current_page?("/achievements") %>
          <%= link_to "Achievements", "/achievements", class: "whatch-nav-link whatch-nav-item-active" %>
          <% else %>
          <%= link_to "Achievements", "/achievements", class: "whatch-nav-link" %>
          <% end %>
        </li>
        <!-- IMPORTANT: remember to insert the proper path below -->
        <li class="nav-item whatch-nav-item">
          <% if current_page?("/saved") %>
          <%= link_to "Saved", saved_movie_path, class: "whatch-nav-link whatch-nav-item-active" %>
          <% else %>
          <%= link_to "Saved", saved_movie_path, class: "whatch-nav-link" %>
          <% end %>
        </li>
        <li class=" whatch-nav-item dropdown">
          <% if current_url.include?("/profile") ||  current_url.include?("/users/edit")%>
          <%= link_to "Profile", "/profile", class: "whatch-nav-item-active dropdown-toggle  whatch-nav-link", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", "/profile", class: "dropdown-item whatch-dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item whatch-dropdown-item" %>
          </div>
          <% else %>
          <%= link_to "Profile", "/profile", class: "whatch-nav-link dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", "/profile", class: "dropdown-item whatch-dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item whatch-dropdown-item" %>
          <% end %>
      <% else %>
        <li class="nav-item whatch-nav-item">
          <%= link_to "Login", new_user_session_path, class: "whatch-nav-link whatch-nav-item" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>